### ISSUE TITLE
希望能增加事件监听接口

### ISSUE THREAD

**Issue by BoltDoggy** [baijunjie/progress.js#1]
就像

```
bjj.progress.on('done', function() {
   // 我自己想要做的
});
```

**Comment by baijunjie** [comment]
嗯，首先谢谢你对这个插件的关注

那么我们先来确定一下是否真的有必要加这个事件。

bjj.progress.done() 是一个手动调用的方法，用于完成进程。
他本身并不基于任何事件。当然页面首次加载的时候会在 window 的 onload 事件中被调用一次

如果你仅仅是想在面首次加载完成的时候做点什么，为什么不直接写成这样呢？
window.addEventListener('load', function() {
   // 我自己想要做的
});

如果是在ajax请求完成时手动调用 bjj.progress.done()，那么应该更不需要这个事件了？

如果添加了'done'这个事件，那么每次调用 bjj.progress.done() 时，这个事件都会触发
bjj.progress.on('done', function() {
   // 我自己想要做的（会被执行多次）
});
